version: '3.4'

services:
  arangodb:
    container_name: api-tcc-arangodb
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
      - /etc/localtime:/etc/localtime
    networks:
      - tcc-network

  api-tcc:
    container_name: api-tcc
    build: .
    command: [ "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8081", "--workers", "1" ]
    ports:
      - "8081:8081"
    environment:
      LOG_LEVEL: INFO
      ARANGODB_HOST: http://arangodb
      ARANGODB_PORT: 8529
      ARANGODB_USER: root
      ARANGODB_PASSWORD: rootpassword
      ARANGODB_DATABASE: TCC
    depends_on:
      - arangodb
    networks:
      - tcc-network

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

networks:
  tcc-network:
    driver: bridge